TEditXna/DependencyChecker.cs
TEditXna/MainWindow.xaml
TEditXna/View/WorldPropertiesView.xaml

Adds support to locate textures via the registry if the GOG.com version is installed.
Also corrects some minor GUI issues -- "Show Tiles" and "Show Liquid" in the Display menu, and correct selection for CrimsonBG in the World Properties panel.

GOG support/UI Fix

---

TEditXna/DependencyChecker.cs
TEditXna/Terraria/World.Settings.cs
TEditXna/ViewModel/WorldViewModel.cs
TEditXna/settings.xml

Not everyone knows where Steam Cloud worlds are stored, so this makes it easier.  Not compatible with OS X, but now there's a single function where it could be fixed.

Added SteamUserId to settings.xml, which enables opening worlds stored in Steam Cloud as the default folder

---

TEditXna/View/WorldRenderXna.xaml.cs

A little bit of whitespace goes a long way towards readability.
Miscellaneous clean up in `LoadResourceTextures()` and `DrawSprites()`

Misc. cleanup WorldRenderXna.xaml.cs for readability

---

TEditXna/Editor/Clipboard/ClipboardManager.cs
TEditXna/Editor/MouseTile.cs
TEditXna/Terraria/Objects/TileProperty.cs
TEditXna/Terraria/World.Settings.cs

When the clipboard "Paste Wire" is disabled, the code was still pasting the buffer's wiring rather than the original wiring in the world.
With all the properties that are now available, we should probably refactor PasteBufferIntoWorld to selectively paste rather than a "clone & restore."

Fix pasting wires (issue #666) and display full herb names

---

TEditXna/Editor/MouseTile.cs
TEditXna/Terraria/Objects/TileProperty.cs
TEditXna/Terraria/World.Settings.cs
TEditXna/settings.xml

I rewrote what I did in #667 so it's more generalized:
For Framed tiles, UseFrameName can be set so the editor displays the framename rather than the tilename on mouseovers
- Example: Display "Frozen Chest, Locked" rather than simply "Chest"
- Currently enabled for herbs and chests.  I didn't do any memory usage tests, but it seems like putting all framed tiles into the dictionary would be a bad idea
For tiles that UseFrameName, an optional FrameNamePostfix can be set, which is appended to the framename
- For example, herbs of id 82 display as (seed) and herbs of id 84 display as (bloom)

Generalized the capability to display framename on mouseover

---

TEditXna/Editor/Plugins/FindChestWithPlugin.cs
TEditXna/Editor/Plugins/FindChestWithPluginResultView.xaml
TEditXna/Editor/Plugins/FindChestWithPluginResultView.xaml.cs
TEditXna/Editor/Plugins/FindChestWithPluginView.xaml
TEditXna/Editor/Plugins/FindChestWithPluginView.xaml.cs
TEditXna/TEditXna.csproj
TEditXna/ViewModel/ViewModelLocator.cs

I created a simple Plugin to search the World for a specific item in all the chests.
You start the plugin, a window opens and asks for the name of the item.
After you start the search a new window pops up with the coordinates of all found chests.
A neat addition would be to double click on the coordinate of a chest and the view would automatically focus the chest in the XNAView. I didn't want to destroy your architecture so I made no changes or tries there.

Added a Plugin to search for a specific item in all the chests

---

TEditXna/Terraria/KillTally.cs

Hi,
This is just a very simple edit to display monsters never killed.
It could be useful for banner hunters, or for achievements (like Gelatin World Tour).

Complete tally with monsters never killed

---

LICENSE
README

I was checking the license before contributing, and noticed that the link provided in README is dead. It redirects to [Microsoft's Openness portal](http://www.microsoft.com/en-us/openness/default.aspx).
Instead of correcting the link, I would like to propose the addition of a LICENSE file. This file is a copy of the [Ms-PL license as found on opensource.org](https://opensource.org/licenses/MS-PL).

Add project's Ms-PL license as a file, to replace broken link

---

TEditXna/View/WorldRenderXna.xaml.cs

When the `SizeChanged` event of the XNA viewport control is fired, the graphics device will be reset to the new size. The `Reset()` method appears to be the only way to resize the viewport (or technically, the backbuffer) after init.
This fixes #651, where [growing and then shrinking the window incorrectly resizes the viewport](https://gfycat.com/MisguidedMammothGoose).
This fix was done using Visual Studio Community 2015 and tested on Windows 10 x64 without any compile or runtime exceptions. I tested window resizing, toggling the sidebar and tools (e.g. selections), with no issues found.
This can probably be done better. Resetting the device on every resize event appears to leak memory. Tested by loading a world and resizing the window for at least 15 seconds:
* **Without fix**: [Private …

Fix #651 - Reset XNA graphics device to new viewport paramters on resize

---

build_beta.bat

The change is just a minor fix, so that all the Execution Policy crud is just plainly ignored. Useful for making building just a little easier, and the scope is auto-limited to just this instance, so no permanent changes are made to the system's Execution Policy.

Bypass Execution Policy

---

TEditXna/Terraria/World.Properties.cs
TEditXna/View/WorldPropertiesView.xaml

this makes it easier to change a worlds guid, to use it paralllel to the original loaded world. if guid is not chanded then problems occur with the players maps

made world id editable + added editable GUID to property view

---

src/TEdit/Editor/Plugins/ReplaceAllPlugin.cs

Added support for adding paint selection to replaced tiles. (https://github.com/TEdit/Terraria-Map-Editor/issues/1465)
Bugfix: Replaced instance of TilePicker.TileMaskMode with TilePicker.WallMaskMode to match expected functionality.
Changed loop variables to only iterate over tiles contained within current selection area (or all tiles if no current selection)

Replace All Tiles Plugin Fix

---

src/TEdit/View/SaveAsVersion.xaml

I have added the remaining versions to the SaveAsVersions GUI. This should complete the vision for this feature.
Future: Create a way to dynamically update this list.

Added Save Options To SaveAsVersion GUI

---

src/TEdit/View/WorldRenderXna.xaml.cs

This is a fix for the Buggy, Grubby, Sluggy, Worm, Gold Worm, Enchanted Nightcrawler, Grasshopper, Gold Grasshopper, And Maggot sprites not showing/rendering properly.
Here is an example of the abnormal sprite drawling.
Bellow is a corrected image of the sprite.

Fixed Some NPC Sprite Issues.

---

src/TEdit/TerrariaVersionTileData.json
src/TEdit/ViewModel/WorldViewModel.cs

- Removed Beta Save Type. Rendered Useless As Beta Cannot Save/Load Worlds. Beta Equals v1.0 TileFrames Anyways.
- Tweaked SaveAs Filter Code Reading Custom Alternate World Versions.

Fix For SaveAs Using Alternate World Versions

---

src/TEdit/Editor/Tools/PickerTool.cs

Fix For Issue #1572 - Picker tool on wires treats green as blue and vice versa

---

src/TEdit/Editor/PaintMode.cs
src/TEdit/Editor/TilePicker.cs
src/TEdit/Editor/Tools/PickerTool.cs
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Themes/Templates.xaml
src/TEdit/View/PaintModeView.xaml
src/TEdit/ViewModel/WorldViewModel.Editor.cs

**Features Added:**
• You can now select left, right, and normal facing junction boxes from wire GUI.
• Full support for deleting / adding only selected facing junction boxes.
• Using the picker tool, it will select correct facing junction boxes along side wire types.
• Full Language Support.

Added Junction Box Support Under Wire GUI + Added Picker Support

---

src/TEdit/Editor/Plugins/FindLocationResultView.xaml
src/TEdit/Editor/Plugins/FindTileLocationResultView.xaml
src/TEdit/Editor/Plugins/FindTileLocationResultView.xaml.cs
src/TEdit/Editor/Plugins/FindTileWithPlugin.cs
src/TEdit/Editor/Plugins/FindTileWithPluginView.xaml
src/TEdit/Editor/Plugins/FindTileWithPluginView.xaml.cs
src/TEdit/ViewModel/ViewModelLocator.cs

So I have been getting a ton of requests for an **Find Block** feature / plugin such as the one [TerraMap](https://github.com/TerraMap/windows) has... Similar to the function of _FindChest_ plugin is basically close to what would be needed. In my previous push there where some issues as pointed out.
**Bellow is an image of the plugin within the plugins tab of the GUI.**
**The next image if the window that will popup after clicking the plugin. This is where you can see similarities from the _FindChest_ plugin GUI. As stated in the last revision, we needed a control way to limit the amount of blocks or walls being searched. I have added a numericupdown control for this. The code for this control was barrowed from this [link](https://stackoverflow.com/a/5321605).**
**In the image bellow, we …

Simple "Find Block or Wall" plugin. Revision v2

---

src/TEdit/Editor/Clipboard/ClipboardBuffer.File.cs
src/TEdit/Terraria/World.FileV2.cs
src/TEdit/View/SaveAsVersion.xaml

So it appears that many users have been launching tickets and complaints on discord that schematic exporting has comply broke. Upon further investigation I have confirmed this and have found that if the version attempting to be referenced from the _TerrariaVersionTileData.json_ does not exist or is of a later version then the programs hardcoded values, there is no stopping the reference of that index thus resulting in a null exception. 
To work around this I have added a saving check to check if the world file is not of a higher number then the coded in values for THIS version of the program. If it is, my workaround is to just simply use the highest version we have on code.
Its VERY IMPORTANT to update _TerrariaVersionTileData.json_ & _WorldFileV2.cs_. 
Within _WorldFileV2.cs_ make sure …

Fix for World and Schematic Saving of Latest Versions.

---

src/TEdit/ViewModel/WorldViewModel.Editor.cs

This is a simple exclusion to the `SetPixelAutomatic()` function.
I'm sure this liquid exclusion for tiles feature is still relevant, however without removing it entirely, a simple if exclusion was added.
**Affected tiles are:**
- Vines (52)
- Jungle Vines (62)
- Hallowed Vines (115)
- Crimson Vine (205)
- Vine Rope (353)
- Vine Flowers (382)
- Silk Rope (365)
- Web Rope (366)

Fix for issue #1525 - Can't draw liquids over certain vine/rope tiles

---

src/TEdit/Terraria/World.FileV2.cs
src/TEdit/Terraria/World.Settings.cs

Changed the old static `public const uint CompatibleVersion = 248` to `public static readonly uint CompatibleVersion;` and addressed in upon the loading class that handles `TerrariaVersionTileData.json` while initializing.
Please review this before pushing. I want this to be a _STABLE_ solution not something that will cause later issues.
Bellow is the application displaying the proper latest version.

Adds Future Automation To Updating Static "CompatibleVersion"

---

src/TEdit/Editor/Tools/MorphTool.cs

Simple fix for the morph tool. Restores functionality for all biomes as it properly should for the effected walls:
```
Clean ID | Walls Effected
---------------------------------------------------
212      | 188, 192, 200, 280, 288
---------------------------------------------------
213      | 189, 193, 201, 281, 289
---------------------------------------------------
214      | 190, 194, 202, 282, 290
---------------------------------------------------
215      | 191, 195, 203, 283, 291
---------------------------------------------------
```

Fix for issue #1617 - Unable to purify 'certain' walls by using biome morph

---

src/TEdit/Editor/Plugins/FindTileLocationResultView.xaml
src/TEdit/Editor/Plugins/FindTileLocationResultView.xaml.cs
src/TEdit/Editor/Plugins/FindTileWithPlugin.cs

This simply adds a count to the final search of the plugin.
**Before Changes:**
**After Changes:**

Added TotalCount to the Find Block or Wall Plugin

---

src/TEdit/MainWindow.xaml
src/TEdit/MainWindow.xaml.cs

-Added "AllowDrop" tag and "Drop" event handler to the <Window>
-Implemented the "WorldFileDrop" Function that is called when "Drop" Event occurs on <Window>
Now when a file is dropped into the TEdit window, it will call the "LoadWorld" Function inside of the "WorldViewModel" class.
The file path of the dropped file is passed into that as a parameter. It appears to work the same as clicking on "File>Open" and selecting the file you want to open.

Added Drag + Drop To Open World File Functionality to TEdit

---

src/TEdit/MainWindow.xaml
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/View/WorldRenderXna.xaml.cs
src/TEdit/ViewModel/WorldViewModel.cs

When viewing a single layer of wire, there should not be any transparency happening to the wires. Even when multiple wire layers are enabled, all disabled layers should not be causing any transparency. This has been fixed as seen below.
**Before:**
**After:**
A new layer option was added. This simply allows users to toggle on or off the ire merging feature.
**Enabled:**
**Disabled:**
I have removed the transparency from single wire junction boxes.
This change keeps it more cannon to the games view and it's interpretation of the junction boxes wiring logic.

Added Wire Transparency Toggle & Fixed Single Wire Layers

---

src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Terraria/World.FileV2.cs
src/TEdit/Terraria/World.Properties.cs
src/TEdit/Terraria/World.cs
src/TEdit/View/WorldPropertiesView.xaml

As many people request, I have added a checkbox to allow for overwriting the "safe" cave levels.
Bellow is an image of the new checkbox.
Bellow is the warning prompt that shows when checking the checkbox:
Further in this push, I have fixes a few important LoadHeaderFlags such as the `SavedTaxCollector` flag being incorrect.

Added "Allow Unsafe Values" For Cave Levels & Fixed 1.2.4.1

---

src/TEdit/Terraria/World.FileV1.cs

Simplify the v0 save to match the v0 load. Fix a spelling issue in items.
Tests pass
Binary identical pre and post save.

V0 Save fixes

---

src/TEdit/BestiaryData.json

The Mystic Frog was missing from the current bestiary list. Now gets 100% when completing the bestiary.

Update bestiary data to 1.4.4.2.

---

src/TEdit/Configuration/MorphConfiguration.cs
src/TEdit/Editor/Tools/MorphTool.cs
src/TEdit/morphSettings.json

Added the ability to add `"hasGravity": true` to morphSettings.json. This is used for the desert to preserve the gravity of sand.
[Demo GIF - Imgur](https://i.imgur.com/HsPRDEP.gif)

Added ["hasGravity": true] object to morphSettings.json.

---

src/TEdit/settings.xml

Added plurals to tile names where applicable. Makes the sprite selection grid more intuitive, in my opinion.
Non-exhaustive list of TODOs
* 129 Crystal Shard — Subsprite Gelatin Crystal horizontal animation
* 139 Music Box — Most sprites missing from styles grid
* 207 Water Fountain — Only off sprites are showing in styles grid
* 270 Firefly in a Bottle — Horizontal animation
* 271 Lightning Bug in a Bottle — Horizontal animation
* 349 Mushroom Statue — Horizontal animation
* 373 Water Drip — Doesn't have a sprite, when selected fallbacks to last selected sprite
* 374 Lava Drip — Doesn't have a sprite, when selected fallbacks to last selected sprite
* 375 Honey Drip — Doesn't have a sprite, when selected fallbacks to last selected sprite
* 388 Tall Gate (Closed) — Fix left variety …

Update settings.xml, style proposition

---

src/TEdit/npcData.json

Eater of Worlds data would be wiped from a player's bestiary upon saving it, even if no edits were made at all, and any previous kills would also be removed. This fixes that issue.

Fixed Eater of Worlds being wiped from bestiary when saving in TEdit

---

src/TEdit/Editor/Plugins/FindTileWithPlugin.cs

Now filters the frame's full name (name + variety? + anchor?). The `frame.ToString()` is implicit at string interpolation.

Update FindTileWithPlugin search

---

src/TEdit/Editor/Plugins/FindTileLocationResultView.xaml.cs

After 253be23424fc097d3c714aed52e865b7692e748a item string can have two colons. Now we make sure we're always getting the last split element

Fix FindTileLocation results zoom

---

src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Terraria/World.Properties.cs
src/TEdit/View/WorldPropertiesView.xaml

Fixed an issue in `World.Properties` and updated the language files to rename `Mobile` to `Android World`.
IOS worlds are different from android.

Fixed issues with the "Mobile" checkbox.

---

src/TEdit/Editor/Plugins/RandomizerPlugin.cs
src/TEdit/Editor/Plugins/RandomizerPluginView.xaml
src/TEdit/Editor/Plugins/RandomizerPluginView.xaml.cs
src/TEdit/settings.xml

In this pull request I have fixed a few bugs with the world randomizer, as well as adding a few new options:
New features:
- Added option to not randomize into disappearing tiles. (Ice rod ice, mystical flute snake rope)
- Added option to satisfy conditions for tiles that have them. (Vines have to hang from grass etc.)
- Added option to support gravity blocks. (Sand, slush, money piles)
Fixes:
- Fixed the randomizer rolling tiles into id `-1`, causing them to disappear
- Fixed the randomizer ignoring the "Randomize walls" checkbox and doing it always anyway

World randomizer update

---

src/TEdit/Terraria/World.Properties.cs

This issue will close issue #1534 - Gap Between Layer Backgrounds on TEdit Generated Worlds.
This issue is caused by the `MaxCavernLevel` reaching a hardcoded maximum for the cavern slider control. On the remix and zenith world seeds the maximum was found to be higher.
Bellow I have hard coded a mod to show the readings from Terraria on the layer depths.

Fix for gap between layer backgrounds Zenith wlds.

---

src/TEdit/Terraria/World.FileV1.cs
src/TEdit/TerrariaVersionTileData.json
src/TEdit/View/Popups/SaveAsVersion.xaml

**About This PR:**
- This PR fixed issues regarding not being able to edit V0 worlds once downgraded or saved. 
- Furthermore, it also fixes crashes related to downgrading or editing V0 worlds.

Fixes for 1.0 (v0) worlds.

---

src/TEdit/Editor/Plugins/BlockShufflePlugin.cs
src/TEdit/Editor/Plugins/BlockShufflePluginView.xaml
src/TEdit/Editor/Plugins/BlockShufflePluginView.xaml.cs
src/TEdit/ViewModel/ViewModelLocator.cs

Adds a plugin that simply takes all blocks in a selected area, and randomises their position.
The plugin-view also got alphabetically sorted.

Block Shuffle Plugin

---

src/TEdit/Editor/Plugins/TextStatuePlugin.cs
src/TEdit/settings.xml

**Issues Found:**
`4.11.4-beta9` - __Settings.xml__ -> Strings `statues` need changed back to `statue`.
`4.11.4-release` - __Terraria/Objects/FrameProperty.cs__ -> The `public override string ToString()` : `return $"{Name} {Variety} {Anchor.ToString()}".Trim();` was changed.
**Solution:**
Since the FrameProperty change, it added an `:`. `Name[12]` needs changed to `Name[13]`.

Fixed the Generate Text Statues plugin.

---

build.ps1
src/TEdit/TEdit.csproj
src/TEdit/View/Popups/NotificationsWindow.xaml
src/TEdit/View/Sidebar/WorldPropertiesView.xaml

* Fixed `WorldPropertiesView` using `IsAndroid` and not `IsChinese`. Found by @pharuxtan. - Tested and now working.
* Bump version.
* Bump version 4.16.
* Update NotificationsWindow.xaml (`4.14`, `4.15`, `4.16`)

Fixed Chinese world checkbox, version bump, and fixed the news for multiple versions.

---

src/TEdit/Editor/PaintMode.cs
src/TEdit/Editor/TilePicker.cs
src/TEdit/Editor/Tools/PickerTool.cs
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Themes/Templates.xaml
src/TEdit/View/Popups/NotificationsWindow.xaml
src/TEdit/View/TopPanel/PaintModeView.xaml
src/TEdit/ViewModel/WorldViewModel.Editor.cs

This PR adds an liquid amount dropdown to the liquid mode.
Furthermore, the picker tool will now select the percent of water and correctly update the dropdown. Levels are done in 10% increments from 0 to 255.

Added an liquid amount dropdown to liquid mode.

---

src/TEdit/Terraria/World.FileV2.cs

In the world loading routine the world version should be read as a `uint`, not an `int`.
This probably won't ever become a problem, but it's better to fix now than cause a headache years down the line...

Fix reading an int where a uint should be read

---

src/TEdit.Terraria/World.Properties.cs
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/View/Sidebar/WorldPropertiesView.xaml

In this update, the checkbox for `Allow Unsafe Values` has been rebranded into `Use Safe Values Only`. This enables the usage and saving of unsafe values by default and for a toggle to use only the safe values.

Reworked the ground levels to use unsafe levels.

---

src/TEdit.Editor/WorldEditor.cs

Before:
After:
This commit also closes issue: #1916

Fixed the brush tool breaking existing regions.

---

src/TEdit/Editor/Tools/PickerTool.cs

In this PR I have restored the picker tool to how it used to be back in pre-TE4.
This now concludes #1838.

Fixed Picking Up Sprites with the Picker tool.

---

src/TEdit.Terraria/Tile.cs
src/TEdit.Terraria/World.Properties.cs
src/TEdit/Editor/Plugins/ImageToPixelartEditorView.xaml
src/TEdit/Editor/Plugins/ImageToPixelartEditorView.xaml.cs
src/TEdit/MapColors.xml
src/TEdit/View/Popups/NewWorldView.xaml
src/TEdit/View/Popups/NewWorldView.xaml.cs
src/TEdit/ViewModel/WorldViewModel.cs

In this PR, I have added a ton of new features to the UI for the "New World" dialog. It includes various controls to set parameters for world generation, including hills, caves, underworld features, and ores.
- **World Name:** Input for the name of the world.
- **World Id (Seed):** Input for the seed value.
- **Width & Height:** Sliders to adjust the dimensions of the world.
- **Surface Level:** Slider to set the surface level of the world.
- **Cavern Level:** Slider to set the cavern level of the world.
- **Hill Terrain Size:** Slider to adjust the size of hill terrain.
- **Add Grass:** Checkbox to enable/disable grass generation on hills.
- **Add Walls:** Checkbox to enable/disable wall generation.
- **Generate Caves (slow):** Checkbox to enable/disable cave generation.
- **Cave …

Added Custom World Generation Options For New Worlds.

---

src/TEdit/MainWindow.xaml
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/View/Popups/NewWorldView.xaml
src/TEdit/View/Popups/NewWorldView.xaml.cs
src/TEdit/ViewModel/WorldViewModel.cs

Made a simple change to make the `new world` GUI less intimidating to new users who are used to the old TEdit new world layout.
- The GUI is collapsed by default.
This change is an ese of access change for people to simply toggle on or off all the wire states.

Collapsible Custom World-Gen + Toggle All Wires Layer.

---

src/TEdit/MainWindow.xaml
src/TEdit/MainWindow.xaml.cs
src/TEdit/View/Popups/UVEditorWindow.xaml
src/TEdit/View/Popups/UVEditorWindow.xaml.cs

This tool will allow you to change a tiles UV and watch it move live within the editor.
- Frame Editor includes full UNDO / REDO support.
The frame editor pop is opened by selecting at least one tile on the map and by clicking the `Frame` textbox.
**Controls:**
- "^" button subtracts each of the current tiles "V" by the value in the "V" textbox.
- "v" button adds each of the current tiles "V" by the value in the "V" textbox.
- ">" button adds each of the current tiles "U" by the value in the "U" textbox.
- "<" button subtracts each of the current tiles "U" by the value in the "U" textbox.
- "Set Values" button sets all the tiles UV manually to any value in the the "U" or "V" textbox's.
- "Selected Frames" textbox shows a visual of all the UVs being shifted around.
- "Cancel" button simply …

Added a Live Frame Editor.

---

src/TEdit/Editor/Clipboard/ClipboardManager.cs

**The fixed desired function:**

Fixed a missing check for pasting only sprites.

---

src/TEdit/settings.xml

This simple fix makes normal and deep paints look apart and closely to that of the in-game. To do this, I simply took the color of each `deep paint` and applied a ~25% shift toward white. Please see the formula bellow.
_Formula:_
```ini
newChannel = original + (255 − original) × 0.25
```
**New Proposed Color Change:**

Non-deep paints, lightened ~25% toward white.

---

src/TEdit/Editor/Plugins/ImageToPixelartEditorView.xaml.cs

This is to resolve the following error within the *Image To Pixelart* plugin:
```js
System.FormatException: The input string '1.0' was not in a correct format.
at System.Double.Parse(String s)
at ImageToPixelartEditorView.ConvertPixelArt(…)
```
It has been concluded that this error has been caused by a `CurrentCulture` issue.
By default `Double.Parse(string)` uses the thread’s `CurrentCulture`, so:
- On en-US Windows: `Double.Parse("1.0")` = `1.0`
- On de-DE Windows, `Double.Parse("1.0")` → `FormatException (expects "1,0")`
Using **double.Parse(SigmaEquals.Text**`, CultureInfo.InvariantCulture`**);** resolves this issue.

Fixed an unhandled 'CurrentCulture' exception.

---

src/TEdit.Editor/Clipboard/ClipboardBuffer.cs
src/TEdit/Editor/Clipboard/ClipboardManager.cs
src/TEdit/Editor/Plugins/HouseGenPlugin.cs
src/TEdit/Editor/Plugins/ImageToPixelartEditorView.xaml.cs
src/TEdit/Editor/Undo/UndoManager.cs
src/TEdit/MainWindow.xaml
src/TEdit/MainWindow.xaml.cs
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.es-ES.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Render/PixelMap.cs
src/TEdit/Render/RenderMiniMap.cs
src/TEdit/View/Popups/FilterWindow.xaml
src/TEdit/View/Popups/FilterWindow.xaml.cs
src/TEdit/View/Popups/UVEditorWindow.xaml
src/TEdit/View/WorldRenderXna.xaml.cs
src/TEdit/ViewModel/FilterManager.cs
src/TEdit/ViewModel/GrayscaleManager.cs
src/TEdit/ViewModel/WorldViewModel.Commands.cs
src/TEdit/ViewModel/WorldViewModel.Editor.cs

This tool allows you to filter what tiles, walls, liquids, and wires are displayed on TEdits world view.
- Advanced Filter includes full **HIDE** / **GRAYSCALE** support as well as **TRANSPARENT** / **CUSTOM** backgrounds.
<p align="center">
</p>
**NOTE:** Activating the filter **DOES NOT** allow the selection to only select filtered entrees by _default_.
-  The _Filter Clipboard_ checkbox allows this feature.
<p align="center">
</p>
**Controls:**
- "Tiles/Walls/Liquids/Wires" tabs navigate to list views of their categorical entrees.
- "Check All" button simply checks all entrees checkboxes within the sections list view.
- "Uncheck All" button simply unchecks all entrees checkboxes within the sections list view.
- "Name: + Textbox" - Sorts the list view based on the users input .
- …

Added an Advanced Filter Feature. Added Frame Editor Language Support.

---

src/TEdit/Editor/Clipboard/ClipboardManager.cs
src/TEdit/View/Popups/FilterWindow.xaml.cs
src/TEdit/ViewModel/FilterManager.cs

Simple typo fix of a property name.
`FilerClipboard` -> `FilterClipboard`

Updated a Property Name.

---

src/TEdit.Terraria/World.FileV2.cs
src/TEdit/Properties/Language.Designer.cs
src/TEdit/Properties/Language.ar-BH.resx
src/TEdit/Properties/Language.de-DE.resx
src/TEdit/Properties/Language.en.resx
src/TEdit/Properties/Language.es-ES.resx
src/TEdit/Properties/Language.pl-PL.resx
src/TEdit/Properties/Language.pt-BR.resx
src/TEdit/Properties/Language.resx
src/TEdit/Properties/Language.ru-RU.resx
src/TEdit/Properties/Language.zh-CN.resx
src/TEdit/Render/PixelMap.cs
src/TEdit/Render/RenderMiniMap.cs
src/TEdit/View/Popups/FilterWindow.xaml
src/TEdit/View/Popups/FilterWindow.xaml.cs
src/TEdit/View/WorldRenderXna.xaml.cs
src/TEdit/ViewModel/FilterManager.cs
src/TEdit/ViewModel/WorldViewModel.Editor.cs

When upgrading worlds from `V0` or `V1` to `V2`, some world properties such as *World Seed* and *NPC Name* are null. This PR includes added checks and fixes to this issue restoring the ability to upgrade "old" worlds via TEdit.
- Tested with a world file from `world v67`. Future checks may be needed for even older files.

Added "Sprites" to The Advanced Filter. Fixed World Upgrading.

---

src/TEdit/Editor/Clipboard/ClipboardManager.cs

Adds the ability for ([Added "Sprites" to The Advanced Filter](https://github.com/TEdit/Terraria-Map-Editor/commit/5c7d659f266c9197b5fff8c96611d02d7cc2c72b)) 5c7d659f266c9197b5fff8c96611d02d7cc2c72b to work with the clipboard filtering support b81d857.

Added clipboard filtering support to sprites.

---

src/TEdit/App.xaml.cs
src/TEdit/DependencyChecker.cs

Within Tedit5.X+, the `AltC` tag is never defined before its value is read, thus breaking alt content locations.

Fixed AltC Path Issue.
