TEdit/Terraria-Map-Editor

TEdit3Installer/Product.wxs, TEditXna/Properties/AssemblyInfo.cs, TEditXna/ViewModel/WorldViewModel.cs, TEditXna/settings.xml
Update to settings.xml (new items and new friendly NPC).  Tile and wall
data to follow later.
=> 1.3 Items/NPC

TEdit3Installer/Product.wxs, TEditXna/Properties/AssemblyInfo.cs, TEditXna/ViewModel/WorldViewModel.cs, TEditXna/settings.xml
Also added some new stuff to "Analysis" but not everything is there.
UI needs to be updated (I DID wrote an update, but managed to delete it by accident)
=> Updated Map load/save to Terraria 1.3 file format

TEditXna/TEditXna.csproj, TEditXna/Terraria/TileEntity.cs, TEditXna/Terraria/World.FileV2.cs, TEditXna/Terraria/World.Properties.cs, TEditXna/Terraria/World.cs, TEditXna/Terraria/WorldAnalysis.cs, TEditXna/View/WorldPropertiesView.xaml
Updated World Properties tab for new data points
=> UI Changes

TEditXna/Editor/MaskMode.cs, TEditXna/Editor/Plugins/ReplaceAllPlugin.cs, TEditXna/ViewModel/WorldViewModel.Editor.cs, TEditXna/settings.xml
- Implements issue #490, "not matching" mask mode
- Increase default app resolution because Windows XP was 4 releases ago
=> New "Not Matching" mask mode, updated default resolution

TEditXna/ViewModel/WorldViewModel.Editor.cs
I added parentheses to the logic for the "Not Matching" MaskMode, which fixes issues #490 and #659.
There's a stupid number of commits only because I'm a Git newb.
=> Fixes Issue #490, #659

TEditXna/MainWindow.xaml, TEditXna/View/WorldRenderXna.xaml.cs
tie actuator visibility into show wires option
=> Actuator Rendering

TEditXna/Editor/Clipboard/ClipboardBuffer.File.cs
schematic loading fix for #670
=> Schematic Fix

TEditXna/Terraria/World.FileV2.cs
Fixes using new tiles in old map.... re #683
=> Quick Fix for Issue #683

TEditXna/View/WorldRenderXna.xaml.cs
Add simple sky, rock, cavern and underground textures to rendering
=> Add simple background rendering

TEditXna/Terraria/World.FileV2.cs, TEditXna/Terraria/World.Properties.cs, TEditXna/Terraria/WorldAnalysis.cs, TEditXna/View/WorldRenderXna.xaml.cs, TEditXna/settings.xml
fix for brickstyle rendering issues, were missing the solid = true flag which is required to load the brickstyle
=> Fix for #686

TEditXna/View/WorldRenderXna.xaml.cs, TEditXna/settings.xml
=> Rendering Updates

TEditXna/View/WorldRenderXna.xaml.cs, TEditXna/settings.xml
*Reordered Tile section of XML for consistency and readability
*Added missing flags here and there in tiles
*Minor rendering update to Palm Trees
=> XML Update

TEditXna/Terraria/World.cs, TEditXna/Terraria/WorldAnalysis.cs, TEditXna/settings.xml
Can't always get things right the first time
*Few things wrong in Tile causing TEdit to crash
=> Settings XML Fix

TEditXna/settings.xml
Should be final update of tiles for new update
=> Settings.xml Update

TEditXna/Terraria/World.FileV2.cs, TEditXna/Terraria/World.cs
=> Fix Saving of New Logic Sensors

TEditXna/Terraria/World.Settings.cs, TEditXna/settings.xml
more sprites, including tiles that have multiple tile sizes
Closes #809
Closes #825
=> Sprite Mapping Update

README.md
Indicate current version and support for specific Terraria and World file versions.
=> Minor README changes 

TEditXna/Terraria/Tile.cs, TEditXna/View/WorldRenderXna.xaml.cs
Cactus on Crimsand wasn't rendering properly
=> Crimson Cactus

TEditXna/Terraria/World.cs
was improperly handling Weighted Pressure Plates
=> Fixes #858

TEditXna/Editor/Tools/ArrowTool.cs, TEditXna/MainWindow.xaml, TEditXna/TEditXna.csproj, TEditXna/Terraria/TileEntity.cs, TEditXna/Terraria/World.FileV2.cs, TEditXna/Terraria/World.Settings.cs, TEditXna/Terraria/World.cs, TEditXna/Terraria/WorldAnalysis.cs, TEditXna/Themes/Templates.xaml, TEditXna/View/SpecialTileView.xaml, TEditXna/View/SpecialTileView.xaml.cs, TEditXna/View/WorldRenderXna.xaml.cs, TEditXna/ViewModel/WorldViewModel.Commands.cs, TEditXna/ViewModel/WorldViewModel.cs
Combine Chest, Signs, Item Frame and Mannequin Editing into one Tab
=> Add Item Frame and Mannequin Editing

TEditXna/Terraria/World.FileV2.cs, TEditXna/Terraria/World.Properties.cs, TEditXna/Terraria/World.cs, TEditXna/View/WorldPropertiesView.xaml, TEditXna/settings.xml
NO SAVE CODE
not fully release ready, will read files, but not save them
=> 1.3.4 Update

TEditXna/Editor/Clipboard/ClipboardBuffer.cs, TEditXna/Editor/Clipboard/ClipboardManager.cs, TEditXna/Editor/Tools/ArrowTool.cs, TEditXna/Terraria/Tile.cs, TEditXna/Terraria/TileEntity.cs, TEditXna/Terraria/World.cs, TEditXna/ViewModel/WorldViewModel.Commands.cs
=> Clipboard Updates

TEditXna/Editor/Clipboard/ClipboardBuffer.cs, TEditXna/Editor/Clipboard/ClipboardManager.cs, TEditXna/Terraria/World.cs
=> Fix buggy chest clipboard

TEditXna/Properties/AssemblyInfo.cs, TEditXna/Terraria/World.FileV2.cs
=> More 1.3.5.1 Updates

TEditXna/Editor/Tools/ArrowTool.cs, TEditXna/Editor/Tools/SpriteTool.cs, TEditXna/Terraria/World.cs, TEditXna/View/SpecialTileView.xaml, TEditXna/View/WorldRenderXna.xaml.cs, TEditXna/ViewModel/WorldViewModel.Commands.cs, TEditXna/ViewModel/WorldViewModel.cs, TEditXna/settings.xml
fix christmas tree in sprite tool and add editing to special tiles tab
=> Fix Christmas Trees

TEditXna/View/WorldPropertiesView.xaml, TEditXna/settings.xml
Master difficulty int value fixed.
=> XML ID Fixes

src/TEdit/writeablebitmapwpf/MoreExtensions.cs
Fix crash when no parent directory exsist.
=> Fix crash when no parent directory exsist.

src/TEdit/View/WorldRenderXna.xaml.cs
Added code to use older zoom functionality if shift is held when scroll wheel is scrolled.
=> Update scrollwheel zoom functionality.

src/TEdit/MainWindow.xaml, src/TEdit/MainWindow.xaml.cs, src/TEdit/Render/RenderMiniMap.cs
This adjusts the minimap resolution to be more consistent and allows for clicking on the minimap to move the main map.
=> Update minimap to allow click to move main map.

src/TEdit/ViewModel/BestiaryViewModel.cs
=> Fix To The Complete Bestiary Issue.

src/TEdit/Properties/Language.ru-RU.resx
Suggestions made from issue https://github.com/TEdit/Terraria-Map-Editor/issues/1631
=> Fixed Some Russian Spelling Issues. - Translation errors #1631

src/TEdit/Configuration/SaveConfiguration.cs, src/TEdit/Terraria/World.FileV2.cs
This fixes saving frame data for legacy versions.
=> fix frames for old versions

src/TEdit/Editor/Plugins/FindChestWithPlugin.cs, src/TEdit/Editor/Plugins/FindChestWithPluginView.xaml, src/TEdit/Editor/Plugins/FindChestWithPluginView.xaml.cs, src/TEdit/Editor/Plugins/FindLocationResultView.xaml.cs, src/TEdit/Editor/Plugins/FindPlanteraBulbPlugin.cs
Bellow is a screenshot of the new checkbox option. 
Bellow is an example when using the new feature.
=> Added a "Distance" from spawn checkbox to "Find Chest With" plugin

src/TEdit/Terraria/World.FileV2.cs
=> Progress to fix 1.2.3 - 1.2.4.1

src/TEdit/Editor/PaintMode.cs, src/TEdit/Editor/TilePicker.cs, src/TEdit/Themes/Templates.xaml, src/TEdit/View/PaintModeView.xaml, src/TEdit/ViewModel/WorldViewModel.Editor.cs
Co-authored-by: DannyRuss <33048298+RussDev7@users.noreply.github.com>
=> Update for Wire replace functionality

src/TEdit/Terraria/World.FileV2.cs
This solves and closes issue #1645.
=> Fix For Bamboo Fences Turning Into Green Mossy Walls.

src/TEdit/Editor/Plugins/FindTileWithPluginView.xaml, src/TEdit/Editor/Plugins/RemoveTileWithPlugin.cs, src/TEdit/Editor/Plugins/RemoveTileWithPluginView.xaml, src/TEdit/Editor/Plugins/RemoveTileWithPluginView.xaml.cs, src/TEdit/View/WorldRenderXna.xaml.cs, src/TEdit/ViewModel/ViewModelLocator.cs
I have added a plugin to find and remove specified sprites, tiles, or walls. 
Furthermore in this update I have added an invalid texture safety net for GetTiletextureColor. Some of the text for other plugins was also adjusted. This post would resolve #1679.
=> Added a "Remove sprite, tile, or walls" plugin.

build.ps1, src/TEdit/App.config, src/TEdit/Configuration/BestiaryData.cs, src/TEdit/Configuration/MorphConfiguration.cs, src/TEdit/Configuration/SaveConfiguration.cs, src/TEdit/Configuration/SaveVersionData.cs, src/TEdit/Editor/Tools/MorphTool.cs, src/TEdit/MainWindow.xaml, src/TEdit/Properties/Language.Designer.cs, src/TEdit/Properties/Language.ar-BH.resx, src/TEdit/Properties/Language.de-DE.resx, src/TEdit/Properties/Language.en.resx, src/TEdit/Properties/Language.pl-PL.resx, src/TEdit/Properties/Language.pt-BR.resx, src/TEdit/Properties/Language.resx, src/TEdit/Properties/Language.ru-RU.resx, src/TEdit/Properties/Language.zh-CN.resx, src/TEdit/Properties/Settings.Designer.cs, src/TEdit/Properties/Settings.settings, src/TEdit/TEdit.csproj, src/TEdit/Terraria/World.Settings.cs, src/TEdit/View/WorldRenderXna.xaml.cs, src/TEdit/ViewModel/WorldViewModel.cs, src/TEdit/morphSettings.json
- Morph tool updates initial work for #533
- option to use texture colors instead of settings.xml colors
ensure #1688 is fixed before merging
=> Morph tool updates

src/TEdit/morphSettings.json
Fixed up some wrong morph's with the help of @YokujinKaze.
=> Morph tool updates.

build.ps1, src/TEdit/MainWindow.xaml, src/TEdit/Terraria/World.FileV2.cs, src/TEdit/Terraria/World.Properties.cs, src/TEdit/View/BestiaryEditor.xaml
- Should fix kill tally
- widen control panel area
=> Kill tally fix

src/TEdit/morphSettings.json
reverted my mistake renaming GlowingMushroom
added some remaining ambient objects
added herbs
added placeholder for future morphs
fixed pumpkin having the wrong id
=> fixes and additions to biome morpher

src/TEdit/morphSettings.json
Willow and Sakura trees added to crimson/corruption
=> Willow and Sakura trees added

src/TEdit/morphSettings.json
added functional forest morph
added partial snow and desert morphs
=> Forest Morpher Update

src/TEdit/ViewModel/WorldViewModel.cs
Pull world title if world file doesn't exist
=> Update SaveAs dialog

src/TEdit/ViewModel/WorldViewModel.cs
Pull world title if world file doesn't exist (similar to e399a3f5785fa012adce96562da92d7713c9d897)
=> Update SaveAsVersion dialog

src/TEdit/Terraria/Objects/FrameProperty.cs
Remove "None" suffix from anchorless frames names
=> Update frame string

src/TEdit/Terraria/Objects/FrameProperty.cs
=> Fix FrameProperty.cs

src/TEdit/Terraria/World.FileV2.cs, src/TEdit/Terraria/World.Properties.cs
=> Renamed improper variable names.

src/TEdit/View/WorldRenderXna.xaml.cs, src/TEdit/ViewModel/WorldViewModel.Editor.cs
=> Fixed issues with saving and rendering of wall coatings

src/TEdit/Terraria/WorldAnalysis.cs
=> Fixed the formatting of the wiring within WorldAnalysis.

src/TEdit/Terraria/CreativePowers.cs, src/TEdit/ViewModel/CreativePowersViewModel.cs
This pull finally resolves the two broken creative powers sliders.
* Enemy Difficultly
* Time Speed
=> Fixed time speed and difficulty creative powers.

src/TEdit/Framework/XamlConverters.cs, src/TEdit/Themes/Templates.xaml, src/TEdit/ViewModel/WorldViewModel.Editor.cs, src/TEdit/ViewModel/WorldViewModel.cs
Fixes tile selection not working in 5.0.0-beta2
Fixes #1902
Fixes #1899
Fixes #1899
=> Fix Tile Selection Dropdown

src/TEdit.Terraria/World.Properties.cs
=> Fix missing RaisePropertyChanged events

src/TEdit/Editor/Plugins/CleanseWorldPlugin.cs, src/TEdit/Editor/Tools/MorphTool.cs, src/TEdit/ViewModel/ViewModelLocator.cs
The following plugin when used will cleanse the whole world to purity.
- Supports Undo & Redo.
=> Added a cleanse world plugin.

src/TEdit.Terraria/World.cs, src/TEdit/ViewModel/WorldViewModel.cs
Before (Stuck on validating):
After (Proper report):
- The `Save` method was synchronous, which could block the UI thread and prevent progress updates from being reported in real-time.
- **Method**: `SaveAsync`
- **Description**: Converted the `Save` method to an asynchronous method to allow non-blocking execution and better handling of progress updates.
- **Description**: Added `progress?.Report(...)` at various stages to report updates during the save operation, including resetting time, saving the world, and completing the save process.
- **Change**: Ensured all file operations (creating temp files, copying, deleting) are handled within a `lock` statement to maintain thread safety.
- **Fix**: Prevented issues with concurrent file access.
- The `SaveWorldThreaded` method used …
=> Fixed World Progress Reporting and Asynchronous Saving.

src/TEdit/Editor/Plugins/PlayerMapRenderer.cs, src/TEdit/ViewModel/ViewModelLocator.cs
This plugin is designed to render the players minimap (.map) file entirely from TEdit. 
- Prompt will ask you to select a player name. This is to determine the player to save the map too.
- Not selecting player file cancels operation.
- Painted blocks are represented properly.
This _finally_ concludes an old feature post #1641.
=> Added a Player .map Renderer Plugin.
